name: peak-ros

services:
  peak-ros:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
      args:
        - ROS2_WORKSPACE_DIR=${ROS2_WORKSPACE_DIR}
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.001'
    #      memory: 500M
    #    reservations:
    #      cpus: '0.0001'
    #      memory: 100M
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY
      - 'ROS2_WORKSPACE_DIR=${ROS2_WORKSPACE_DIR}'
      - 'ROS_DOMAIN_ID=${ROS_DOMAIN_ID}'
      - 'RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}'
    volumes:
      - $XAUTHORITY:/root/.Xauthority
      - ../src:${ROS2_WORKSPACE_DIR}/src
    #command: sleep infinity
    command: ros2 launch peak_ros init.launch.xml
    #restart: unless-stopped
